services:
  mariadb-example:
    image: mariadb:latest
    container_name: mariadb-example
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "admin123"
      MARIADB_USER: "raka"
      MARIADB_PASSWORD: "raka123"
      MARIADB_DATABASE: "raka_db"

  adminer-example:
    image: adminer
    container_name: adminer-example
    ports:
      - "8080:8080"
