services:
  mariadb-example:
    image: mariadb:latest
    container_name: mariadb-example
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "admin123"
      MARIADB_USER: "raka"
      MARIADB_PASSWORD: "raka123"
      MARIADB_DATABASE: "raka_db"