services:  
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "3307:3306"
    environment:
      MONGO_INITDB_ROOT_USERNAME: raka
      MONGO_INITDB_ROOT_PASSWORD: raka
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example
  
  mongo-express-example:
    image: mongo-express:latest
    container_name: mongo-express-example
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: raka
      ME_CONFIG_MONGODB_ADMINUPASSWORD: raka
      ME_CONFIG_MONGODB_SERVER: mongodb1
    depends_on:
      - mongodb1
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge