services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "3307:3306"
    environment:
      MONGO_INITDB_ROOT_USERNAME: raka
      MONGO_INITDB_ROOT_PASSWORD: raka
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo_data1:/data/db"

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "3308:3306"
    environment:
      MONGO_INITDB_ROOT_USERNAME: raka
      MONGO_INITDB_ROOT_PASSWORD: raka
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo_data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo_data1
   mongo-data2:
    name: mongo_data12